### ISSUE TITLE
Unable to update vm dev-demo01 with vmid None=int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by PC-Admin** [application-research/ehi-proxmaas#15]
Completely unable to make VMs now it seems. :/

```
TASK [Create the requested VMs] **************************************************************************************************
failed: [localhost] (item=1) => {"ansible_loop_var": "item", "changed": false, "item": 1, "msg": "Unable to update vm dev-demo01 with vmid None=int() argument must be a string, a bytes-like object or a real number, not 'NoneType'", "vmid": null}
failed: [localhost] (item=2) => {"ansible_loop_var": "item", "changed": false, "item": 2, "msg": "Unable to update vm dev-demo02 with vmid None=int() argument must be a string, a bytes-like object or a real number, not 'NoneType'", "vmid": null}
failed: [localhost] (item=3) => {"ansible_loop_var": "item", "changed": false, "item": 3, "msg": "Unable to update vm dev-demo03 with vmid None=int() argument must be a string, a bytes-like object or a real number, not 'NoneType'", "vmid": null}
```

Tried inside and outside of the venv I created, exact same bug.

Tried forcing the last community.general collection to v0.6.4 (what i was using last time this worked), exact same bug.

**Comment by PC-Admin** [comment]
Okay this is being caused by the last update we did where we added the "update: true" line to proxmox_kvm.

We'll have to make it default to false if the VM doesn't already exist...

**Comment by PC-Admin** [comment]
Seems like you can't probe the Proxmox API to check if this VM already exists because that required a VMID (which we don't have since it hasn't yet been created)...

This is a crude method that 'pre-creates' the VM with `update: false`, I had to do something similar to this before since proxmox_kvm is just a really jank module tbh:
```
    - name: "Pre-create the requested VMs, needed due to: https://github.com/ansible-collections/community.general/issues/6147#issuecomment-1534092201"
      delegate_to: localhost
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        # api_password: "{{ proxmox_password }}"
        api_host: proxmox.estuary.tech
        timeout: 60
        name: "{{ vm_name }}{{ '%02d' | format(item) }}"
        node: "{{ proxmox_nodes[item % 8] }}"
        scsihw: "virtio-scsi-single"
        scsi: "{{ scsi_disk_layout }}"
        net:
          net0: 'bridge=vmbr0,virtio,mtu=1,firewall=1'
        update: false
      loop: "{{ range(starting_number_target | int, vm_count | int + starting_number_target | int) | list }}"

    - name: Create the requested VMs
      delegate_to: localhost
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        # api_password: "{{ proxmox_password }}"
        api_host: proxmox.estuary.tech
        timeout: 60
        name: "{{ vm_name }}{{ '%02d' | format(item) }}"
        memory: "{{ amount_of_memory | int }}"
        balloon: "{{ minimum_memory | default(0) | int }}"
        cores: "{{ number_of_vcpus | int }}"
        agent: true
        description: "{{ vm_description | default('A VM spawned by ProxMAAS and Ansible') }}"
        onboot: false
        # Set machines to boot from network first, then hard disk
        boot: nc
        cpu: host
        node: "{{ proxmox_nodes[item % 8] }}"
        scsihw: "virtio-scsi-single"
        scsi: "{{ scsi_disk_layout }}"
        net:
          net0: 'bridge=vmbr0,virtio,mtu=1,firewall=1'
        bios: ovmf
        efidisk0:
          storage: vm-storage
          format: raw
          efitype: 4m
          pre_enrolled_keys: false
        update: true
      loop: "{{ range(starting_number_target | int, vm_count | int + starting_number_target | int) | list }}"
      register: vm_result
```
