### ISSUE TITLE
destroy.yml isn't destroying well enough!

### ISSUE THREAD

**Issue by PC-Admin** [application-research/ehi-proxmaas#2]
a reminder at the end of destroy to delete in MASS too might be handy!

**Comment by PC-Admin** [comment]
Fails with:
```
TASK [Set the starting number for the VMs] ******************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'vm_count is not defined or vm_count.length == 0' failed. The error was: error while evaluating conditional (vm_count is not defined or vm_count.length == 0): 'str object' has no attribute 'length'. 'str object' has no attribute 'length'\n\nThe error appears to be in '/home/pcadmin/MyVault/Estuary_LIVE/LATEST/estuary-hosted-infrastructure/playbooks/ehi-proxmaas/destroy.yml': line 65, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Set the starting number for the VMs\n      ^ here\n"}
```

could also use a section to import the related vars if needed:
```
- name: Delete Proxmox Virtual Machines
  hosts: proxmox_clients
  connection: local

  vars_files:
    - "vars/production-ehi/{{ machine_details | default('dev-demo') }}.yml"
```

the whole thing could use a tune-up, but it's not a high priority for now
